# Lista de Exercícios

In [2]:
import numpy as np

### Exercício 1 - Considere o vetor [1, 2, 3, 4, 5], construa um novo vetor com três elementos 0 (zero) entre cada elemento do vetor.

**Resposta:**

```
array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])
```

### Exercício 2 - Crie uma matriz quadrada de 8 X 8 e preencha com o padrão de tabuleiro de xadrez, utilizando 0 (zero) para casas brancas e 1 (um) para casas pretas.

**Resposta:**

```
array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])
```

### Exercício 3 - Dado um array de 2 dimensões, como trocar 2 linhas entre si?

**Resposta:**

array inicial:
```
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])
```

array com as linhas 0 e 1 trocadas entre si:
```
array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])
```

array com as linhas 2 e 3 trocadas entre si:
```
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])
```

### Exercício 4 - Dado um array de 2 dimensões, como trocar 2 colunas entre si?

**Resposta:**

array inicial:
```
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])
```

array com as colunas 2 e 3 trocadas entre si:
```
array([[ 0,  1,  3,  2,  4],
       [ 5,  6,  8,  7,  9],
       [10, 11, 13, 12, 14],
       [15, 16, 18, 17, 19],
       [20, 21, 23, 22, 24]])
```

### Exercício 5 - Dado o array [1, 2, 3] criar o array [[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]]

**Resposta:**

```
array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])
``` 


### Exercício 6 - Dado o array [1, 2, 3] criar o array [[1, 1, 1], [2, 2, 2], [3, 3, 3]]

**Resposta:**

```
array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])
```

### Exercício 7 - Dado o array [4, 95, 37, 64, 42, 19, 55, 38, 46, 83, 48, 67, 98, 21, 10, 88], obtenha todos os itens que estão entre 35 e 55.

**Resposta:**

```
array([37, 42, 38, 46, 48, 55])
```


### Exercicio 8 - Considere um array com 100 elementos inteiros iniciando em 0. Dado um número randômico positivo e flutuante, descubra qual o elemento do array, mais próximo desse número.

In [19]:
arr = np.arange(0,101)
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [4]:
f = np.random.uniform(0,100)
f

91.41992152996067

### Exercicio 9 - Dado um array, substitua todos os valores inferiores a 10 por 10 e todos os valores superiores a 30 por 30.

In [91]:
np.random.seed(100)
arr = np.random.uniform(1, 50, 30)
arr

array([27.62684215, 14.64009987, 21.80136195, 42.39403048,  1.23122395,
        6.95688692, 33.86670515, 41.466785  ,  7.69862289, 29.17957314,
       44.67477576, 11.25090398, 10.08108276,  6.31046763, 11.76517714,
       48.95256545, 40.77247431,  9.42510962, 40.99501269, 14.42961361,
       22.153505  , 47.06146116, 41.06481956, 17.46948556,  9.59511223,
       19.26877027,  1.27873686, 13.36889132, 39.98746292,  1.74749359])

**Resposta**

array inicial:
```
array([27.62684215, 14.64009987, 21.80136195, 42.39403048,  1.23122395,
        6.95688692, 33.86670515, 41.466785  ,  7.69862289, 29.17957314,
       44.67477576, 11.25090398, 10.08108276,  6.31046763, 11.76517714,
       48.95256545, 40.77247431,  9.42510962, 40.99501269, 14.42961361,
       22.153505  , 47.06146116, 41.06481956, 17.46948556,  9.59511223,
       19.26877027,  1.27873686, 13.36889132, 39.98746292,  1.74749359])
```

array após as substituições:
```
array([27.62684215, 14.64009987, 21.80136195, 30.        , 10.        ,
       10.        , 30.        , 30.        , 10.        , 29.17957314,
       30.        , 11.25090398, 10.08108276, 10.        , 11.76517714,
       30.        , 30.        , 10.        , 30.        , 14.42961361,
       22.153505  , 30.        , 30.        , 17.46948556, 10.        ,
       19.26877027, 10.        , 13.36889132, 30.        , 10.        ])
```

### Exercicio 10 - Para calcular o determinante de matrizes de terceira ordem, utiliza-se a chamada regra de Sarrus, que resulta no seguinte cálculo:

$
D\left(\begin{array}{cc} 
a & b & c \\
d & e & f \\
g & h & i
\end{array}\right)
$ = (aei + bfg + cdh) - (afh + bdi + ceg)

### Escreva uma função para calcular o determinante de uma matriz quadrada de ordem 3.