In [1]:
import numpy as np

## 1 - Crie um vetor com 10 elementos 0.

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

```
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
```

## 2 - Crie um vetor com 10 elementos 0 e inicialize o quinto elemento com o valor 1.

In [4]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

```
array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])
```

## 3 - Crie um vetor com valores em sequencia de 10 à 49.

In [41]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

```
array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])
```

## 4 - Crie um vetor com valores inteiros de 50 à 0.

In [64]:
np.arange(50, -1, -1)

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

```
array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])
```


## 5 - Crie um vetor com valores inteiros de 0 à 49 em seguida inverta a ordem do vetor.

In [71]:
a = np.arange(0,50, dtype=int)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [73]:
reverse_order = np.sort(a)[::-1]
reverse_order
#ou
np.flip(a)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

```
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])
       
array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])
```

## 6 - Crie uma matriz 3 x 3 com valores de 1 à 9.

In [49]:
np.arange(1, 10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

```
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])
```

## 7 - Dada o vetor [1, 3, 0, 3, 0, 3, 2, 0, 1, 0], descubra os índices dos elementos diferentes de zero.

In [76]:
a = np.array([1, 3, 0, 3, 0, 3, 2, 0, 1, 0])
np.nonzero(a)
#ou
np.where(a!=0)

(array([0, 1, 3, 5, 6, 8], dtype=int64),)

```
array([0, 1, 3, 5, 6, 8], dtype=int64)
```

## 8 - Crie uma matriz 3 x 3 x 3 com números aleatórios.

In [84]:
np.random.rand(3,3,3)
#ou
np.random.randn(3,3,3)
#ou
np.random.random((3,3,3))

array([[[0.78455022, 0.45059174, 0.86688819],
        [0.59344871, 0.88375884, 0.86996868],
        [0.82734069, 0.71655513, 0.66736909]],

       [[0.14685032, 0.91082425, 0.21072964],
        [0.01097287, 0.37070625, 0.17515969],
        [0.34697586, 0.02008126, 0.75190093]],

       [[0.30094724, 0.36710381, 0.63212017],
        [0.05265363, 0.92105419, 0.76143586],
        [0.62049478, 0.51907197, 0.22766385]]])

Exemplo:
```
array([[[0.61286554, 0.74921735, 0.61223858],
        [0.96047489, 0.65628431, 0.79342544],
        [0.70941175, 0.98583943, 0.00318382]],

       [[0.85867772, 0.93941609, 0.30006033],
        [0.79160418, 0.0865738 , 0.69892442],
        [0.33265707, 0.25932833, 0.11447914]],

       [[0.24026643, 0.23737787, 0.04470459],
        [0.11646793, 0.32991814, 0.85027852],
        [0.25262905, 0.1805445 , 0.40050341]]])
```

## 9 - Crie um vetor de tamanho 10 com números aleatórios em ordenados em ordem crescente.

In [89]:
a = np.random.random(10)
a.sort()
a
#ou
np.sort(a)

array([0.01389593, 0.29033578, 0.45144811, 0.59960377, 0.65114222,
       0.68738168, 0.82519438, 0.82799286, 0.93896884, 0.95881926])

Exemplo:
```
array([0.56239709, 0.36663249, 0.24432617, 0.43788321, 0.89709646,
       0.58901959, 0.26398762, 0.82502151, 0.3666227 , 0.47548132])
       
array([0.24432617, 0.26398762, 0.3666227 , 0.36663249, 0.43788321,
       0.47548132, 0.56239709, 0.58901959, 0.82502151, 0.89709646])
```