In [2]:
import numpy as np

In [4]:
lista = [1,2,3]
lista

[1, 2, 3]

In [5]:
type(lista)

list

In [6]:
arr = np.array(lista)
arr

array([1, 2, 3])

In [7]:
matriz = [[1,2],[3,4],[5,6]]
matriz

[[1, 2], [3, 4], [5, 6]]

In [8]:
np.array(matriz)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros(3, dtype=int)

array([0, 0, 0])

In [14]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [17]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.ones((2,3), dtype=str)

array([['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')

In [19]:
np.ones((2,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

# linspace()

In [21]:
np.linspace(0, 50, 5)

array([ 0. , 12.5, 25. , 37.5, 50. ])

In [23]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [24]:
np.eye(8, dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

In [25]:
np.random

<module 'numpy.random' from 'C:\\Programas\\python\\3.7.4\\lib\\site-packages\\numpy\\random\\__init__.py'>

In [26]:
dir(np.random)

['BitGenerator',
 'Generator',
 'MT19937',
 'PCG64',
 'Philox',
 'RandomState',
 'SFC64',
 'SeedSequence',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_bounded_integers',
 '_common',
 '_generator',
 '_mt19937',
 '_pcg64',
 '_philox',
 '_pickle',
 '_sfc64',
 'beta',
 'binomial',
 'bit_generator',
 'bytes',
 'chisquare',
 'choice',
 'default_rng',
 'dirichlet',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_state',
 'shuffle',
 'standard_cauchy',
 'standard_exponential',
 'stand

In [27]:
np.random.rand(5)

array([0.92187529, 0.2919201 , 0.40166718, 0.4150193 , 0.12921351])

In [28]:
np.random.rand(1,10)

array([[0.69850898, 0.98739385, 0.16387889, 0.65862926, 0.38990665,
        0.73799194, 0.37684152, 0.9774899 , 0.7734055 , 0.51932861]])

In [30]:
np.random.rand(3,10)

array([[0.30863077, 0.92815438, 0.20747825, 0.9168591 , 0.9094487 ,
        0.34851755, 0.47949842, 0.61927669, 0.0211369 , 0.31363703],
       [0.03671988, 0.16662532, 0.39469572, 0.51461044, 0.01918976,
        0.07508721, 0.8645934 , 0.25880258, 0.96545205, 0.88865474],
       [0.48233081, 0.30084895, 0.1829539 , 0.04082115, 0.95855404,
        0.60930046, 0.98375354, 0.94193976, 0.65151189, 0.7078379 ]])

In [33]:
abs(np.random.rand(1,10) * 100)

array([[79.53103831, 60.17681819, 83.64236749,  3.61627923, 31.59279347,
        49.58791356,  8.79596697, 35.07353794, 65.43204747, 52.23483053]])

In [35]:
np.random.randn()

-1.0375201994292742

In [36]:
np.random.randn(5)

array([-0.37729813,  0.10853647,  0.19419382, -1.22379114, -0.64672151])

In [38]:
np.random.randint(1,10)

6

In [54]:
np.random.randint(1,1000, size=(3,3))

array([[720, 401, 875],
       [895, 776, 284],
       [979, 927,  91]])

In [55]:
np.random.randint(1,1000, (3,3))

array([[602, 762, 306],
       [570, 823,  95],
       [790, 187, 554]])

In [56]:
a = np.random.randint(1,1000, (3,3))

In [58]:
a

array([[508, 813, 448],
       [852, 484, 857],
       [831, 660, 376]])

In [59]:
a = np.random.randint(1,1000)

In [61]:
a.shape

AttributeError: 'int' object has no attribute 'shape'

In [62]:
a

560

In [63]:
a = np.random.rand(10) * 10


In [64]:
a.max()

8.703653290683315

In [65]:
a

array([7.27498259, 3.54581068, 8.70365329, 8.61310622, 1.88702682,
       7.67559716, 7.24770811, 1.786408  , 3.49447543, 5.68258638])

In [66]:
a.min()

1.7864079961005974

In [67]:
a.argmax()

2

In [68]:
a[2]

8.703653290683315

In [70]:
a = a.reshape(5,2)

In [71]:
a

array([[7.27498259, 3.54581068],
       [8.70365329, 8.61310622],
       [1.88702682, 7.67559716],
       [7.24770811, 1.786408  ],
       [3.49447543, 5.68258638]])

In [ ]:
a.